


const INTERNAL_ERROR = 'INTERNAL_ERROR'
const SEND_COMMUNITY_INVIT_ERROR = 'SEND_COMMUNITY_INVIT_ERROR'
const LEAVE_COMMUNITY_ERROR = 'LEAVE_COMMUNITY_ERROR'
const DELETE_COMMUNITY_ERROR = 'DELETE_COMMUNITY_ERROR'
const INVALID_INVITATION_CODE = 'INVALID_INVITATION_CODE'
const EXCLUDE_USER_ERROR = 'EXCLUDE_USER_ERROR'


module.exports = {

  INTERNAL_ERROR,
  SEND_COMMUNITY_INVIT_ERROR,
  LEAVE_COMMUNITY_ERROR,
  DELETE_COMMUNITY_ERROR,
  INVALID_INVITATION_CODE,
  EXCLUDE_USER_ERROR
};
