const NAME_MIN = 3;
const NAME_MAX = 60;

// Errors constant name is created from:
// 1: uppercase input name + _ + (eg: NAME)
// 2: error type serverd by joi + _ + (eg: MIN)
// 3: ERROR
// 4: final constant name: NAME_MIN_ERROR

const SENSORNODE_NAME_MIN = 3
const SENSORNODE_NAME_MAX = 60
const SENSORNODE_PRODUCT_MIN = 3
const SENSORNODE_PRODUCT_MAX = 60

const ERROR_UPDATE_SENSORNODE_PAYLOAD = 'ERROR_UPDATE_SENSORNODE_PAYLOAD'

const DELETE_SENSORNODE_AUTHORIZATION_ERROR = 'DELETE_SENSORNODE_AUTHORIZATION_ERROR'
const DELETE_SENSORNODE_ERROR = 'DELETE_SENSORNODE_ERROR'
const INTERNAL_ERROR = 'INTERNAL_ERROR'

module.exports = {
  INTERNAL_ERROR,
  SENSORNODE_NAME_MIN,
  SENSORNODE_NAME_MAX,
  SENSORNODE_PRODUCT_MIN,
  SENSORNODE_PRODUCT_MAX,
  ERROR_UPDATE_SENSORNODE_PAYLOAD,
  DELETE_SENSORNODE_AUTHORIZATION_ERROR,
  DELETE_SENSORNODE_ERROR
};
