const NAME_MIN = 3;
const NAME_MAX = 30;

const PASSWORD_MIN = 8;
const PASSWORD_MAX = 30;
const VERIFICATION_CODE_MIN = 4
const VERIFICATION_CODE_MAX = 8

//GLOBAL ERROR
const INTERNAL_ERROR = 'INTERNAL_ERROR';



//STEP 1 CHECK EMAIL POSSIBILITIES
const EMAIL_AVAILABLE = 'EMAIL_AVAILABLE'
const INVALID_REGISTERUSERNAME_PAYLOAD = 'INVALID_REGISTERUSERNAME_PAYLOAD'
const USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS'

//STEP 2 CHECK REGISTRATION CIDE
const INVALID_REGISTRATION_CODE = 'INVALID_REGISTRATION_CODE'

//STEP 3 PROVIDE PERSONNALE PIC -- OR GO 4
const NO_PICTURE_PROVIDED = 'NO_PICTURE_PROVIDED'

//STEP 4 FINALIZE REGISTRATION
const INVALID_REGISTER_PAYLOAD = 'INVALID_REGISTER_PAYLOAD'
const REGISTRATION_ERROR = 'REGISTRATION_AUTHORIZATION_ERROR'
const REGISTER_SUCCESS = 'CLIENT_CREATED';


module.exports = {
  INVALID_REGISTERUSERNAME_PAYLOAD,
  EMAIL_AVAILABLE,
  NAME_MIN,
  NAME_MAX,
  PASSWORD_MAX,
  PASSWORD_MIN,
  VERIFICATION_CODE_MIN,
  VERIFICATION_CODE_MAX,
  INTERNAL_ERROR,
  REGISTER_SUCCESS,
  USER_ALREADY_EXISTS,
  INVALID_REGISTRATION_CODE,
  REGISTRATION_ERROR,
  NO_PICTURE_PROVIDED
};
