
// Errors constant name is created from:
// 1: uppercase input name + _ + (eg: NAME)
// 2: error type serverd by joi + _ + (eg: MIN)
// 3: ERROR
// 4: final constant name: NAME_MIN_ERROR



const INTERNAL_ERROR = 'INTERNAL_ERROR';

const GET_MASTERNODE_AUTHORIZATION_ERROR = 'GET_MASTERNODE_AUTHORIZATION_ERROR'


const CREATE_MASTERNODE_ERROR = 'CREATE_MASTERNODE_ERROR';
const UPDATE_MASTERNODE_ERROR = 'UPDATE_MASTERNODE_ERROR';
const GENERATE_MASTERNODE_KEY_ERROR = 'GENERATE_MASTERNODE_KEY_ERROR';
const LOAD_MASTERNODES_ERROR = 'LOAD_MASTERNODES_ERROR';


module.exports = {
  INTERNAL_ERROR ,
  GET_MASTERNODE_AUTHORIZATION_ERROR,
  CREATE_MASTERNODE_ERROR,
  UPDATE_MASTERNODE_ERROR ,
  GENERATE_MASTERNODE_KEY_ERROR,
  LOAD_MASTERNODES_ERROR
};
