const NAME_MIN = 3;
const NAME_MAX = 60;
const PASSWORD_MIN = 8;
const PASSWORD_MAX = 30;

const INVALID_CREDENTIALS = 'INVALID_CREDENTIALS';
const SUCCESSFULLY_LOGGED_IN = 'LOGIN_SUCCESS';



module.exports = {
  NAME_MIN,
  NAME_MAX,
  PASSWORD_MAX,
  PASSWORD_MIN,
  INVALID_CREDENTIALS,
  SUCCESSFULLY_LOGGED_IN
};
