const PASSWORD_MIN = 8;
const PASSWORD_MAX = 30;
const VERIFICATION_CODE_MIN = 4
const VERIFICATION_CODE_MAX = 8

const INTERNAL_ERROR = 'INTERNAL_ERROR';



//STEP 1 --> SEND EMAIL
const INVALID_RESETUSERNAME_PAYLOAD = 'INVALID_RESETUSERNAME_PAYLOAD'

//STEP 2 --> VERIFICATION CODE
const INVALID_RESETCODE = 'INVALID_RESETCODE'
const INVALID_RESETCODE_PAYLOAD = 'INVALID_RESETCODE_PAYLOAD'

//STEP 3 --> CHANGE PASSWORD
const NEW_PASSWORD_AUTHORIZATION_ERROR = 'NEW_PASSWORD_AUTHORIZATION_ERROR'
const INVALID_NEWPASSWORD_PAYLOAD = 'INVALID_NEWPASSWORD_PAYLOAD'

module.exports = {
  VERIFICATION_CODE_MIN,
  VERIFICATION_CODE_MAX,
  PASSWORD_MAX,
  PASSWORD_MIN,
  INVALID_RESETUSERNAME_PAYLOAD,
  INTERNAL_ERROR,
  INVALID_RESETCODE,
  INVALID_RESETCODE_PAYLOAD,
  NEW_PASSWORD_AUTHORIZATION_ERROR
};
